<?php


return [
    'access' => [

        'shipping_type-list' => 'shipping_type_list',
        'shipping_type-add' => 'shipping_type_add',
        'shipping_type-edit' => 'shipping_type_edit',
        'shipping_type-delete' => 'shipping_type_delete',

        'flash_sale-list' => 'flash_sale_list',
        'flash_sale-add' => 'flash_sale_add',
        'flash_sale-edit' => 'flash_sale_edit',
        'flash_sale-delete' => 'flash_sale_delete',

        'category-list' => 'category_list',
        'category-add' => 'category_add',
        'category-edit' => 'category_edit',
        'category-delete' => 'category_delete',

        'product-list' => 'product_list',
        'product-add' => 'product_add',
        'product-edit' => 'product_edit',
        'product-delete' => 'product_delete',

        'news-list' => 'news_list',
        'news-add' => 'news_add',
        'news-edit' => 'news_edit',
        'news-delete' => 'news_delete',

        'slider-list' => 'slider_list',
        'slider-add' => 'slider_add',
        'slider-edit' => 'slider_edit',
        'slider-delete' => 'slider_delete',

        'user-list' => 'user_list',
        'user-add' => 'user_add',
        'user-edit' => 'user_edit',
        'user-delete' => 'user_delete',

        'chat-list' => 'chat_list',
        'chat-add' => 'chat_add',
        'chat-edit' => 'chat_edit',
        'chat-delete' => 'chat_delete',

        'employee-list' => 'employee_list',
        'employee-add' => 'employee_add',
        'employee-edit' => 'employee_edit',
        'employee-delete' => 'employee_delete',

        'role-list' => 'role_list',
        'role-add' => 'role_add',
        'role-edit' => 'role_edit',
        'role-delete' => 'role_delete',

        'permission-list' => 'permission_list',
        'permission-add' => 'permission_add',
        'permission-edit' => 'permission_edit',
        'permission-delete' => 'permission_delete',

        'notification-list' => 'notification_list',
        'notification-add' => 'notification_add',
        'notification-edit' => 'notification_edit',
        'notification-delete' => 'notification_delete',

        'logo-list' => 'logo_list',
        'logo-add' => 'logo_add',
        'logo-edit' => 'logo_edit',
        'logo-delete' => 'logo_delete',

        'history_data-list' => 'history_data_list',
        'history_data-add' => 'history_data_add',
        'history_data-edit' => 'history_data_edit',
        'history_data-delete' => 'history_data_delete',

        'order-list' => 'order_list',
        'order-add' => 'order_add',
        'order-edit' => 'order_edit',
        'order-delete' => 'order_delete',

        'type_sale-list' => 'type_sale_list',
        'type_sale-add' => 'type_sale_add',
        'type_sale-edit' => 'type_sale_edit',
        'type_sale-delete' => 'type_sale_delete',

        'voucher-list' => 'voucher_list',
        'voucher-add' => 'voucher_add',
        'voucher-edit' => 'voucher_edit',
        'voucher-delete' => 'voucher_delete',

        'group_user-list' => 'group_user_list',
        'group_user-add' => 'group_user_add',
        'group_user-edit' => 'group_user_edit',
        'group_user-delete' => 'group_user_delete',

        'debt-list' => 'debt_list',
        'debt-add' => 'debt_add',
        'debt-edit' => 'debt_edit',
        'debt-delete' => 'debt_delete',

        'sales_statistics-list' => 'sales_statistics_list',
        'sales_statistics-add' => 'sales_statistics_add',
        'sales_statistics-edit' => 'sales_statistics_edit',
        'sales_statistics-delete' => 'sales_statistics_delete',

        'inventory_statistics-list' => 'inventory_statistics_list',
        'inventory_statistics-add' => 'inventory_statistics_add',
        'inventory_statistics-edit' => 'inventory_statistics_edit',
        'inventory_statistics-delete' => 'inventory_statistics_delete',

        'product_sold_statistics-list' => 'product_sold_statistics_list',
        'product_sold_statistics-add' => 'product_sold_statistics_add',
        'product_sold_statistics-edit' => 'product_sold_statistics_edit',
        'product_sold_statistics-delete' => 'product_sold_statistics_delete',

        'receipt-list' => 'receipt_list',
        'receipt-add' => 'receipt_add',
        'receipt-edit' => 'receipt_edit',
        'receipt-delete' => 'receipt_delete',

        'payment-list' => 'payment_list',
        'payment-add' => 'payment_add',
        'payment-edit' => 'payment_edit',
        'payment-delete' => 'payment_delete',

        'cash_book-list' => 'cash_book_list',
        'cash_book-add' => 'cash_book_add',
        'cash_book-edit' => 'cash_book_edit',
        'cash_book-delete' => 'cash_book_delete',

    ],
    'table_module'=>[
        'shipping_type',
        'flash_sale',
        'category',
        'product',
        'news',
        'slider',
        'user',
        'chat',
        'employee',
        'role',
        'permission',
        'notification',
        'logo',
        'history_data',
        'order',
        'type_sale',
        'voucher',
        'group_user',
        'debt',
        'sales_statistics',
        'inventory_statistics',
        'product_sold_statistics',
        'receipt',
        'payment',
        'cash_book',
    ],

    'table_module_name'=>[
        'Đơn vị vận chuyển',
        'Flash Sale',
        'Danh mục',
        'Sản phẩm',
        'Tin tức',
        'Slider',
        'Khách hàng',
        'Chat',
        'Nhân viên',
        'Vai trò nhân viên',
        'Cấp quyền',
        'Thông báo',
        'Logo',
        'Lịch sử dữ liệu',
        'Đơn hàng',
        'Phân loại giá',
        'Mã giảm giá',
        'Nhóm khách hàng',
        'Công nợ',
        'Thống kê doanh số',
        'Thống kê tồn kho',
        'Thống kê sản phẩm bán theo ngày',
        'Phiếu thu',
        'Phiếu chi',
        'Sổ quỹ',
    ],

    'module_children'=>[
        'list',
        'add',
        'edit',
        'delete',
    ]
];
